---
- name: Generate a SECRET_KEY for NetBox if unspecified
  shell: "set -o pipefail; {{ netbox_python_binary }} {{ netbox_current_path }}/netbox/generate_secret_key.py\
          | tr -d $'\n' > {{ netbox_shared_path }}/generated_secret_key"
  args:
    creates: "{{ netbox_shared_path }}/generated_secret_key"
    executable: /bin/bash
  become: true
  become_user: "{{ netbox_user }}"

- name: Load saved SECRET_KEY
  slurp:
    src: "{{ netbox_shared_path }}/generated_secret_key"
  register: _netbox_secret_key_file

- name: Set netbox_config.SECRET_KEY to generated SECRET_KEY
  set_fact:
    _netbox_config: "{{ _netbox_config | combine({'SECRET_KEY': _netbox_secret_key_file['content'] | b64decode}) }}"
