---
- name: Install required packages for selected NetBox configuration
  dnf:
    name: "{{ _netbox_dnf_packages | flatten }}"
    state: present
    update_cache: true
  vars:
    _netbox_dnf_packages:
      - "{{ 'epel-release' if netbox_install_epel else [] }}"
      - "{{ netbox_python_packages }}"
      - "{{ netbox_packages }}"
      - "{{ netbox_ldap_packages if netbox_ldap_enabled else [] }}"
      - "{{ 'git' if netbox_git else [] }}"
      - "{{ 'acl' if ('SUDO_USER' in ansible_env and ansible_env.SUDO_USER != 'root') else [] }}"
