---
- name: Install required packages for selected NetBox configuration
  apt:
    name: "{{ _netbox_apt_packages | flatten }}"
    state: present
    cache_valid_time: 3600
    update_cache: true
  vars:
    _netbox_apt_packages:
      - "{{ netbox_python_packages }}"
      - "{{ netbox_packages }}"
      - "{{ netbox_ldap_packages if netbox_ldap_enabled else [] }}"
      - "{{ 'git' if netbox_git else [] }}"
      - "{{ 'acl' if ('SUDO_USER' in ansible_env and ansible_env.SUDO_USER != 'root') else [] }}"
