---
- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"

- name: Define netbox_packages
  set_fact:
    netbox_packages: "{{ _netbox_packages | list }}"
  when: netbox_packages is not defined

- name: Define netbox_python_packages
  set_fact:
    netbox_python_packages: "{{ _netbox_python_packages | list }}"
  when: netbox_python_packages is not defined

- name: Define netbox_python_binary
  set_fact:
    netbox_python_binary: "{{ _netbox_python_binary }}"
  when: netbox_python_binary is not defined

- name: Define netbox_ldap_packages
  set_fact:
    netbox_ldap_packages: "{{ _netbox_ldap_packages | list }}"
  when: netbox_ldap_packages is not defined

- name: Define _netbox_config
  set_fact:
    _netbox_config: "{{ netbox_config }}"

- name: Generate list of optional Python dependencies
  set_fact:
    _netbox_python_deps:
      - "{{ netbox_napalm_packages if netbox_napalm_enabled else [] }}"
      - "{{ 'django-auth-ldap' if netbox_ldap_enabled else [] }}"
      - "{{ 'django-storages' if _netbox_storages_module is defined else [] }}"
      - "{{ _netbox_storages_map[_netbox_storages_module] if _netbox_storages_module is defined else [] }}"
      - "{{ netbox_pip_packages }}"

- name: Flatten that list of dependencies
  set_fact:
    _netbox_python_deps: "{{ _netbox_python_deps | flatten }}"

- name: Identify current execution PATH
  shell: "echo $PATH"
  register: _path_exec
  changed_when: false
  check_mode: false

- name: Set a fact for current execution PATH
  set_fact:
    _path: "{{ _path_exec.stdout }}"
  check_mode: false

- name: Capture the current Python interpreter
  set_fact:
    _netbox_global_python: "{{ ansible_python_interpreter }}"
  when: ansible_python_interpreter is defined

- name: Set the execution uwsgi command
  set_fact:
    netbox_uwsgi_cmd: "/usr/bin/env uwsgi"
  when: "not netbox_uwsgi_in_venv | bool"
