---
- hosts: all
  become: true
  roles:
    - geerlingguy.postgresql
    - davidwittman.redis
    - lae.netbox
  vars:
    netbox_stable: true
    netbox_socket: "0.0.0.0:80"
    netbox_superuser_password: netbox
    netbox_config:
      ALLOWED_HOSTS:
        - "{{ inventory_hostname }}"
        # The following should not be used in production, probably.
        # This playbook gets used by Vagrant where we don't know the actual hostname.
        - "*"
      MEDIA_ROOT: "{{ netbox_shared_path }}/media"
      REPORTS_ROOT: "{{ netbox_shared_path }}/reports"
      SCRIPTS_ROOT: "{{ netbox_shared_path }}/scripts"
    netbox_database_socket: "{{ postgresql_unix_socket_directories[0] }}"
    netbox_keep_uwsgi_updated: true
    postgresql_users:
      - name: "{{ netbox_database_user }}"
        role_attr_flags: CREATEDB,NOSUPERUSER
    redis_bind: 127.0.0.1
    redis_version: 6.0.9
    redis_checksum: sha256:dc2bdcf81c620e9f09cfd12e85d3bc631c897b2db7a55218fd8a65eaa37f86dd
  pre_tasks:
    - name: Enable Subscription Manager Repos
      rhsm_repository:
        name: "{{ item }}"
      loop:
        - rhel-*-optional-rpms
        - rhel-*-extras-rpms
      when: "ansible_distribution == 'Red Hat Enterprise Linux'"
    - block:
        - name: Set PostgreSQL facts to use PG10 for RedHat distributions
          set_fact:
            postgresql_version: 10
            postgresql_packages:
              - postgresql10
              - postgresql10-server
              - postgresql10-contrib
              - postgresql10-libs
            postgresql_data_dir: /var/lib/pgsql/10/data
            postgresql_bin_path: /usr/pgsql-10/bin
            postgresql_config_path: /var/lib/pgsql/10/data
            postgresql_daemon: postgresql-10
        - name: Install the EPEL yum repository
          yum:
            name: epel-release
        - name: Install the PostgreSQL yum repository
          yum:
            name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
      when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version =='7'"

# You can use this playbook as-is to setup a full NetBox server, just change
# the FQDN below. It'll accept HTTP requests on specified FQDN.
#
# ansible-playbook -i netbox.example.com, playbook_single_host_deploy.yml
#
# Note that for RH systems, PostgreSQL is installed from upstream.
